version: '3'
services:
  game:
    build:
      context: .
      dockerfile: Dockerfile
    hostname: gamehost
    ports:
      - "8080:8881"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/Game
      SPRING_DATASOURCE_USERNAME: user
      SPRING_DATASOURCE_PASSWORD: password
    depends_on:
      - db

  db:
    image: postgres:latest
    environment:
      POSTGRES_DB: Game
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"